version: "3.7"

services:

  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: xstdev-homebox_server_1
      APP_PORT: 7745
    
  server:
    image: ghcr.io/hay-kot/homebox:latest
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
      - HBOX_LOG_LEVEL=info
      - HBOX_LOG_FORMAT=text
      - HBOX_WEB_MAX_UPLOAD_SIZE=10
    volumes:
      - ${APP_DATA_DIR}/data:/data/
